# Generated by Django 5.1.1 on 2024-09-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('GC', 'Общий осмотр'), ('VC', 'Вакцинация'), ('DC', 'Стоматологическая помощь'), ('SG', 'Хирургия'), ('EM', 'Неотложная помощь'), ('GR', 'Груминг'), ('NC', 'Консультация по питанию'), ('BT', 'Поведенческая коррекция')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('veterinarian', 'Ветеринар'), ('surgeon', 'Хирург'), ('radiologist', 'Рентгенолог'), ('dentist', 'Стоматолог'), ('nurse', 'Медсестра'), ('assistant', 'Ассистент'), ('administrator', 'Администратор')], max_length=255)),
                ('photo', models.ImageField(max_length=255, upload_to='photos-of-specialists/')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos-of-pets/')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_breed', to='api.breed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=1024)),
                ('visit_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_pet', to='api.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_service', to='api.service')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_species', to='api.species'),
        ),
    ]
