# Generated by Django 5.1.1 on 2024-10-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_breed_options_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
